# Generated by Django 5.1.7 on 2025-03-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SustanabilityAction',
            new_name='SustainabilityAction',
        ),
    ]
