# Generated by Django 5.1.7 on 2025-03-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sustanabilityaction_sustainabilityaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SustainabilityAction',
            new_name='DB1',
        ),
    ]
