# Generated by Django 5.1.7 on 2025-03-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_sustainabilityaction_db1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB1',
            new_name='Sustainability',
        ),
    ]
